version: '3'

services:
  pg_db:
    container_name: pg_database
    image: library/postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: FMH_DB
    ports:
      - "5400:5432"
  backend:
    container_name: fmh_backend
    image: ghcr.io/fmh-charity/fmh-backend:latest
    depends_on:
      - pg_db
    environment:
      DB_PORT: 5432
      DB_HOST: pg_database
      DB_USER: postgres
      DB_PASS: 123
  nginx:
    container_name: nginx
    image: nginx:latest
    links:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/src/docker/certs/:/src/certs/
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./build:/opt/front
    depends_on:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"